name: Keep Alive
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  keep-alive:
    name: Keep Alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
